### ISSUE TITLE
Expose relay switch

### ISSUE THREAD

**Issue by maxim-mityutko** [zuidwijk/esphome-doorbell#10]
Hi, it's more of a question, rather than an issue.
Do I understand correctly that if I change the config to expose the relay switch, it will be possible to trigger the bell by other button, not only the one directly connected to the smart doorbell?

https://github.com/zuidwijk/esphome-doorbell/blob/ff7d9514b045b626cac89de5ce04e96895852162/smart-doorbell.yaml#L80C1-L88

**Comment by theautomation** [comment]
I am wondering exactly the same thing, did you figured it out yet?

**Comment by PieterBoeren** [comment]
You can set the relay to 'internal: false', upload it again to the doorbell and then you can switch the relay directly.

**Comment by theautomation** [comment]
Thanks!

**Comment by maxim-mityutko** [comment]
> You can set the relay to 'internal: false', upload it again to the doorbell and then you can switch the relay directly.

awesome! thanks for confirming!
